import { describe, it, expect } from 'vitest'
import { isPpkFile, parsePpk } from './ppk'

// Minimal unencrypted Ed25519 PPK v2 fixture (generated by PuTTYgen)
const ED25519_PPK_V2_UNENCRYPTED = `PuTTY-User-Key-File-2: ssh-ed25519
Encryption: none
Comment: test-key
Public-Lines: 2
AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLGefTB9ea6R
2/JhjxplAb2pO3CfUuW4GRpNPzfRwJoHs0VqAcxI/hh7xjd3kLgpqjuLiFPZx+s
Private-Lines: 1
AAAAIFake/PrivateKeyData==
Private-MAC: 0000000000000000000000000000000000000000`

describe('ppk', () => {
  it('detects PPK file correctly', () => {
    expect(isPpkFile(ED25519_PPK_V2_UNENCRYPTED)).toBe(true)
  })

  it('does not detect PEM as PPK', () => {
    expect(isPpkFile('-----BEGIN PRIVATE KEY-----\nABC\n-----END PRIVATE KEY-----')).toBe(false)
  })

  it('throws meaningful error on MAC mismatch (wrong passphrase)', async () => {
    await expect(parsePpk(ED25519_PPK_V2_UNENCRYPTED, 'wrongpassphrase')).rejects.toThrow()
  })
})

describe('ppk MAC verification', () => {
  it('rejects tampered public key data', async () => {
    const tampered = ED25519_PPK_V2_UNENCRYPTED.replace('Comment: test-key', 'Comment: evil-key')
    await expect(parsePpk(tampered)).rejects.toThrow()
  })
})
